# Generated by Django 5.2.9 on 2025-12-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
